[tool.poetry]
name = "openvpc"
version = "0.1.0"
description = "open vpc service"
authors = ["Roberto Berto <roberto.berto@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
fastapi = "^0.104.1"
sqlalchemy = "^2.0.23"
python-dotenv = "^1.0.0"
aiomysql = "^0.2.0"
uvicorn = "^0.24.0.post1"
alembic = "^1.12.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
