# -*- mode: ruby -*-
# vi: set ft=ruby :

# 172.30.0.0/16 - bloco de ipv4 dos vpc
# 172.30.0.0/24 - primeiro bloco de vpc zona sp1
# 172.30.1.0/24 - primeiro bloco de vpc zona sp2

$script = <<-SHELL
  cfg=/opt/vyatta/sbin/vyatta-cfg-cmd-wrapper  
  $cfg begin
  $cfg set service https api debug
  $cfg set service https api keys id apikey key vyos
  $cfg set service https listen-address $1
  $cfg set service https port 8080
  $cfg commit
  $cfg end
SHELL

Vagrant.configure("2") do |config|

  # VPC na zona sp1
  config.vm.define "vyos_sp1" do |sp1|
    sp1.vm.box = "vyos/current"
    sp1.vm.hostname = "vyos-sp1"
    sp1.vm.network "public_network", ip: "192.168.0.51", bridge: "wlo1"
    # sp1.vm.network "private_network", ip: "172.30.0.4"
    # sp1.vm.network "forwarded_port", guest: 8080, host: 2081
    sp1.ssh.username = "vyos"
    sp1.ssh.password = "vyos"
    sp1.ssh.insert_key = false
    # Outras configurações específicas para a VPC sp1 podem ser adicionadas aqui
    sp1.vm.provision "shell", inline: $script, args: ["192.168.0.51"]
  end

  # VPC na zona sp2
  config.vm.define "vyos_sp2" do |sp2|
    sp2.vm.box = "vyos/current"
    sp2.vm.hostname = "vyos-sp2"
    sp2.vm.network "public_network", ip: "192.168.0.52", bridge: "wlo1"
    # sp2.vm.network "private_network", ip: "172.30.1.4"
    # sp2.vm.network "forwarded_port", guest: 8080, host: 2082
    sp2.ssh.username = "vyos"
    sp2.ssh.password = "vyos"
    sp2.ssh.insert_key = false
    # Outras configurações específicas para a VPC sp2 podem ser adicionadas aqui
    sp2.vm.provision "shell", inline: $script, args: ["192.168.0.52"]
  end
end

  # Configurações glob

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
#Vagrant.configure("2") do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://vagrantcloud.com/search.
  #config.vm.box = "vyos/current"

  #config.ssh.username = "vyos"
  #config.ssh.password = "vyos"
  #config.ssh.insert_key = false


  # Disable automatic box update checking. If you disable this, then
  # boxes will only be checked for updates when the user runs
  # `vagrant box outdated`. This is not recommended.
  # config.vm.box_check_update = false

  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine. In the example below,
  # accessing "localhost:8080" will access port 80 on the guest machine.
  # NOTE: This will enable public access to the opened port
  # config.vm.network "forwarded_port", guest: 80, host: 8080

  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine and only allow access
  # via 127.0.0.1 to disable public access
  # config.vm.network "forwarded_port", guest: 80, host: 8080, host_ip: "127.0.0.1"

  # Create a private network, which allows host-only access to the machine
  # using a specific IP.
  # config.vm.network "private_network", ip: "192.168.33.10"

  # Create a public network, which generally matched to bridged network.
  # Bridged networks make the machine appear as another physical device on
  # your network.
  # config.vm.network "public_network"

  # Share an additional folder to the guest VM. The first argument is
  # the path on the host to the actual folder. The second argument is
  # the path on the guest to mount the folder. And the optional third
  # argument is a set of non-required options.
  # config.vm.synced_folder "../data", "/vagrant_data"

  # Disable the default share of the current code directory. Doing this
  # provides improved isolation between the vagrant box and your host
  # by making sure your Vagrantfile isn't accessable to the vagrant box.
  # If you use this you may want to enable additional shared subfolders as
  # shown above.
  # config.vm.synced_folder ".", "/vagrant", disabled: true

  # Provider-specific configuration so you can fine-tune various
  # backing providers for Vagrant. These expose provider-specific options.
  # Example for VirtualBox:
  #
  # config.vm.provider "virtualbox" do |vb|
  #   # Display the VirtualBox GUI when booting the machine
  #   vb.gui = true
  #
  #   # Customize the amount of memory on the VM:
  #   vb.memory = "1024"
  # end
  #
  # View the documentation for the provider you are using for more
  # information on available options.

  # Enable provisioning with a shell script. Additional provisioners such as
  # Ansible, Chef, Docker, Puppet and Salt are also available. Please see the
  # documentation for more information about their specific syntax and use.
  # config.vm.provision "shell", inline: <<-SHELL
  #   apt-get update
  #   apt-get install -y apache2
  # SHELL
#end
