- name: Configurar interface eth0 no VyOS
  hosts: vyos
  gather_facts: true
  tasks:
    - name: Remover DHCP da interface eth0
      vyos_config:
        lines:
          - set interfaces loopback lo address '127.0.0.2/24'
        save: yes

    - name: Definir IP estático na interface eth0
      vyos_config:
        lines:
          - set interfaces loopback lo address '127.0.0.1/24'
        save: yes



