"""Renomear coluna vpc_name para name

Revision ID: 20d11af6a179
Revises: 
Create Date: 2023-11-07 23:04:07.191741

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '20d11af6a179'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vpcs', sa.Column('name', sa.String(length=255), nullable=True))
    op.drop_index('ix_vpcs_vpc_name', table_name='vpcs')
    op.create_index(op.f('ix_vpcs_name'), 'vpcs', ['name'], unique=True)
    op.drop_column('vpcs', 'vpc_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vpcs', sa.Column('vpc_name', mysql.VARCHAR(length=255), nullable=True))
    op.drop_index(op.f('ix_vpcs_name'), table_name='vpcs')
    op.create_index('ix_vpcs_vpc_name', 'vpcs', ['vpc_name'], unique=False)
    op.drop_column('vpcs', 'name')
    # ### end Alembic commands ###
