"""

Revision ID: 8c03f442f188
Revises: 4bacadd97dd8
Create Date: 2023-11-16 22:27:44.921644

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c03f442f188'
down_revision: Union[str, None] = '4bacadd97dd8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('zone',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('creation_datetime', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_zone_id'), 'zone', ['id'], unique=False)
    op.create_index(op.f('ix_zone_name'), 'zone', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_zone_name'), table_name='zone')
    op.drop_index(op.f('ix_zone_id'), table_name='zone')
    op.drop_table('zone')
    # ### end Alembic commands ###
