"""

Revision ID: 97da78fe3888
Revises: bc4f00065bbd
Create Date: 2023-11-16 23:52:39.428559

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '97da78fe3888'
down_revision: Union[str, None] = 'bc4f00065bbd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_config_param', table_name='config')
    op.create_index(op.f('ix_config_param'), 'config', ['param'], unique=False)
    op.create_unique_constraint('_param_scope_zone_uc', 'config', ['param', 'scope_zone'])
    op.create_index(op.f('ix_config_scope_zone'), 'config', ['scope_zone'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_config_scope_zone'), table_name='config')
    op.drop_constraint('_param_scope_zone_uc', 'config', type_='unique')
    op.drop_index(op.f('ix_config_param'), table_name='config')
    op.create_index('ix_config_param', 'config', ['param'], unique=False)
    # ### end Alembic commands ###
