"""

Revision ID: bc4f00065bbd
Revises: 4d729da5b554
Create Date: 2023-11-16 23:42:22.058380

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'bc4f00065bbd'
down_revision: Union[str, None] = '4d729da5b554'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('config', sa.Column('param', sa.String(length=255), nullable=True))
    op.add_column('config', sa.Column('format', sa.String(length=50), nullable=True))
    op.drop_index('ix_config_param_name', table_name='config')
    op.create_index(op.f('ix_config_param'), 'config', ['param'], unique=True)
    op.drop_column('config', 'value_type')
    op.drop_column('config', 'param_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('config', sa.Column('param_name', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('config', sa.Column('value_type', mysql.VARCHAR(length=50), nullable=True))
    op.drop_index(op.f('ix_config_param'), table_name='config')
    op.create_index('ix_config_param_name', 'config', ['param_name'], unique=False)
    op.drop_column('config', 'format')
    op.drop_column('config', 'param')
    # ### end Alembic commands ###
