"""Renomear tabela vpcs para vpc

Revision ID: fef64b245132
Revises: 20d11af6a179
Create Date: 2023-11-16 21:58:22.018880

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'fef64b245132'
down_revision: Union[str, None] = '20d11af6a179'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vpc',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('device_name_primary', sa.String(length=255), nullable=True),
    sa.Column('device_name_secondary', sa.String(length=255), nullable=True),
    sa.Column('creation_datetime', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vpc_id'), 'vpc', ['id'], unique=False)
    op.create_index(op.f('ix_vpc_name'), 'vpc', ['name'], unique=True)
    op.drop_index('ix_vpcs_id', table_name='vpcs')
    op.drop_index('ix_vpcs_name', table_name='vpcs')
    op.drop_table('vpcs')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vpcs',
    sa.Column('id', mysql.VARCHAR(length=36), nullable=False),
    sa.Column('device_name_primary', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('device_name_secondary', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('creation_datetime', mysql.DATETIME(), nullable=True),
    sa.Column('status', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('name', mysql.VARCHAR(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_vpcs_name', 'vpcs', ['name'], unique=False)
    op.create_index('ix_vpcs_id', 'vpcs', ['id'], unique=False)
    op.drop_index(op.f('ix_vpc_name'), table_name='vpc')
    op.drop_index(op.f('ix_vpc_id'), table_name='vpc')
    op.drop_table('vpc')
    # ### end Alembic commands ###
