- name: Configurar interface eth0 no VyOS
  hosts: vyos
  gather_facts: false
  tasks:
    - name: Remover DHCP da interface eth0
      vyos_config:
        lines:
          - delete interfaces ethernet eth0 address dhcp
        save: yes

    - name: Definir IP estático na interface eth0
      vyos_config:
        lines:
          - set interfaces ethernet eth0 address '127.0.0.1/24'
        save: yes



